import { describe, expect, it } from 'vitest'
import { render, screen } from '@testing-library/react'
import { ExplainSubViewDisclaimer } from '../ExplainSubViewDisclaimer'

describe('ExplainSubViewDisclaimer', () => {
  it('renders the exact spec-locked disclaimer text', () => {
    render(<ExplainSubViewDisclaimer />)
    // Match the substring — whitespace between span lines is normalized by RTL
    expect(
      screen.getByText(
        /This explanation was generated by an AI trained on biblical scholarship\./,
      ),
    ).toBeInTheDocument()
    expect(
      screen.getByText(/Use it as a starting point, not a final answer\./),
    ).toBeInTheDocument()
  })

  it('has no dismiss button (non-dismissible)', () => {
    render(<ExplainSubViewDisclaimer />)
    expect(screen.queryByRole('button')).toBeNull()
  })

  it('applies the muted text-white/40 styling', () => {
    const { container } = render(<ExplainSubViewDisclaimer />)
    const paragraph = container.querySelector('p')
    expect(paragraph?.className).toContain('text-white/40')
  })
})
