import { beforeEach, describe, expect, it, vi } from 'vitest'
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'

const { mockUseExplainPassage, mockGenerateExplanation } = vi.hoisted(() => ({
  mockUseExplainPassage: vi.fn(),
  mockGenerateExplanation: vi.fn(),
}))

vi.mock('@/hooks/bible/useExplainPassage', async () => {
  const actual = await vi.importActual<
    typeof import('@/hooks/bible/useExplainPassage')
  >('@/hooks/bible/useExplainPassage')
  return {
    ...actual,
    useExplainPassage: (ref: string, text: string) =>
      mockUseExplainPassage(ref, text),
  }
})

vi.mock('@/lib/ai/geminiClient', () => ({
  generateExplanation: (...args: unknown[]) => mockGenerateExplanation(...args),
}))

// Stub reduced motion so the skeleton renders deterministically
vi.mock('@/hooks/useReducedMotion', () => ({
  useReducedMotion: () => false,
}))

import { ExplainSubView } from '../ExplainSubView'
import type { VerseSelection } from '@/types/verse-actions'
import type { ExplainErrorKind } from '@/hooks/bible/useExplainPassage'

const SMALL_SELECTION: VerseSelection = {
  book: '1-corinthians',
  bookName: '1 Corinthians',
  chapter: 13,
  startVerse: 4,
  endVerse: 7,
  verses: [
    { number: 4, text: 'Love is patient and is kind.' },
    { number: 5, text: "doesn't behave itself inappropriately." },
    { number: 6, text: "doesn't rejoice in unrighteousness." },
    { number: 7, text: 'bears all things.' },
  ],
}

function mockState(
  status: 'loading' | 'success' | 'error',
  opts: {
    content?: string
    errorKind?: ExplainErrorKind
    errorMessage?: string
    retry?: () => void
  } = {},
) {
  mockUseExplainPassage.mockReturnValue({
    status,
    result:
      status === 'success'
        ? { content: opts.content ?? 'test content', model: 'gemini-2.5-flash-lite' }
        : null,
    errorKind: status === 'error' ? opts.errorKind ?? null : null,
    errorMessage: status === 'error' ? opts.errorMessage ?? null : null,
    retry: opts.retry ?? vi.fn(),
  })
}

beforeEach(() => {
  mockUseExplainPassage.mockReset()
  mockGenerateExplanation.mockReset()
})

describe('ExplainSubView — structural', () => {
  it('renders reference and verse text in the context strip', () => {
    mockState('loading')
    const { container } = render(
      <ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />,
    )
    expect(container.textContent).toContain('1 Corinthians 13:4')
    expect(container.textContent).toContain('Love is patient')
  })

  it('component body starts with a plain div (no self-rendered back button)', () => {
    mockState('loading')
    const { container } = render(
      <ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />,
    )
    expect(container.firstChild?.nodeName).toBe('DIV')
    // The sub-view does NOT render its own back button with aria-label="Back"
    expect(screen.queryByRole('button', { name: /^back$/i })).toBeNull()
  })

  it('component body does not contain a self-rendered close X button', () => {
    mockState('loading')
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    expect(screen.queryByRole('button', { name: /close/i })).toBeNull()
  })
})

describe('ExplainSubView — loading state', () => {
  it('renders the Thinking label', () => {
    mockState('loading')
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    expect(screen.getByText('Thinking…')).toBeInTheDocument()
  })

  it('does NOT render the disclaimer during loading', () => {
    mockState('loading')
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    expect(
      screen.queryByText(/This explanation was generated by an AI/),
    ).toBeNull()
  })
})

describe('ExplainSubView — success state', () => {
  it('renders the explanation body', () => {
    mockState('success', { content: 'Paul is writing to a factional church.' })
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    expect(
      screen.getByText('Paul is writing to a factional church.'),
    ).toBeInTheDocument()
  })

  it('renders the disclaimer on success', () => {
    mockState('success', { content: 'test' })
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    expect(
      screen.getByText(/This explanation was generated by an AI/),
    ).toBeInTheDocument()
  })

  it('uses whitespace-pre-wrap to preserve paragraph breaks', () => {
    mockState('success', { content: 'Para 1.\n\nPara 2.' })
    const { container } = render(
      <ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />,
    )
    const body = container.querySelector('.whitespace-pre-wrap')
    expect(body).not.toBeNull()
  })

  it('escapes HTML in content (React default, no dangerouslySetInnerHTML)', () => {
    mockState('success', { content: '<script>alert(1)</script>' })
    const { container } = render(
      <ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />,
    )
    // The literal text appears in the DOM (escaped), and no <script> tag is created
    expect(container.textContent).toContain('<script>alert(1)</script>')
    expect(container.querySelector('script')).toBeNull()
  })
})

describe('ExplainSubView — error states', () => {
  it('renders network error copy', () => {
    mockState('error', {
      errorKind: 'network',
      errorMessage: "Couldn't load an explanation right now. Check your connection and try again.",
    })
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    expect(
      screen.getByText(/Couldn't load an explanation right now/),
    ).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /try again/i })).toBeInTheDocument()
  })

  it('renders safety block error copy', () => {
    mockState('error', {
      errorKind: 'safety',
      errorMessage:
        'This passage is too difficult for our AI helper to explain well. Consider reading a scholarly commentary or asking a trusted teacher.',
    })
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    expect(
      screen.getByText(/too difficult for our AI helper/),
    ).toBeInTheDocument()
  })

  it('renders timeout error copy', () => {
    mockState('error', {
      errorKind: 'timeout',
      errorMessage: 'The request took too long. Try again in a moment.',
    })
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    expect(screen.getByText(/took too long/)).toBeInTheDocument()
  })

  it('renders api error copy', () => {
    mockState('error', {
      errorKind: 'api',
      errorMessage: 'This feature is temporarily unavailable. Try again in a few minutes.',
    })
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    expect(screen.getByText(/temporarily unavailable/)).toBeInTheDocument()
  })

  it('renders unavailable (key-missing) copy', () => {
    mockState('error', {
      errorKind: 'unavailable',
      errorMessage: 'This feature is temporarily unavailable. Try again in a few minutes.',
    })
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    expect(screen.getByText(/temporarily unavailable/)).toBeInTheDocument()
  })

  it('clicking retry calls the hook retry function', async () => {
    const retry = vi.fn()
    mockState('error', {
      errorKind: 'network',
      errorMessage: 'x',
      retry,
    })
    const user = userEvent.setup()
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    await user.click(screen.getByRole('button', { name: /try again/i }))
    expect(retry).toHaveBeenCalledTimes(1)
  })

  it('does NOT render the disclaimer in error state', () => {
    mockState('error', { errorKind: 'api', errorMessage: 'x' })
    render(<ExplainSubView selection={SMALL_SELECTION} onBack={vi.fn()} />)
    expect(
      screen.queryByText(/This explanation was generated by an AI/),
    ).toBeNull()
  })
})

describe('ExplainSubView — 20-verse cap', () => {
  it('over-limit selection shows error without firing the hook', () => {
    // Build a 25-verse selection (exceeds the 20-verse cap)
    const largeSelection: VerseSelection = {
      ...SMALL_SELECTION,
      startVerse: 1,
      endVerse: 25,
      verses: Array.from({ length: 25 }, (_, i) => ({
        number: i + 1,
        text: `Verse ${i + 1} text.`,
      })),
    }

    // Hook is still called (rules-of-hooks) but with empty args
    mockState('loading')
    render(<ExplainSubView selection={largeSelection} onBack={vi.fn()} />)

    expect(
      screen.getByText(/Please select 20 or fewer verses to explain/),
    ).toBeInTheDocument()

    // Hook was called with empty strings (over-limit guard) and the real
    // Gemini client was never reached
    expect(mockUseExplainPassage).toHaveBeenCalledWith('', '')
    expect(mockGenerateExplanation).not.toHaveBeenCalled()
  })

  it('at-limit selection (exactly 20) does fire the hook', () => {
    const atLimit: VerseSelection = {
      ...SMALL_SELECTION,
      startVerse: 1,
      endVerse: 20,
      verses: Array.from({ length: 20 }, (_, i) => ({
        number: i + 1,
        text: `v${i + 1}`,
      })),
    }
    mockState('loading')
    render(<ExplainSubView selection={atLimit} onBack={vi.fn()} />)

    // Hook was called with the real reference and verse text — NOT empty strings
    const [[ref, text]] = mockUseExplainPassage.mock.calls
    expect(ref).not.toBe('')
    expect(text).not.toBe('')
  })
})
