import { describe, expect, it } from 'vitest'
import { render, screen } from '@testing-library/react'
import { ReflectSubViewDisclaimer } from '../ReflectSubViewDisclaimer'

describe('ReflectSubViewDisclaimer', () => {
  it('renders the exact spec-locked disclaimer text', () => {
    render(<ReflectSubViewDisclaimer />)
    expect(
      screen.getByText(/This reflection was generated by an AI\./),
    ).toBeInTheDocument()
  })

  it('contains the load-bearing "maybe not your way" clause', () => {
    render(<ReflectSubViewDisclaimer />)
    // This specific clause is the load-bearing pastoral move — belt-and-
    // suspenders assertion so accidental paraphrasing fails loudly.
    expect(screen.getByText(/maybe not your way/)).toBeInTheDocument()
  })

  it('contains the full non-dismissible phrasing pattern', () => {
    render(<ReflectSubViewDisclaimer />)
    expect(
      screen.getByText(/not the only way, not the best way, and maybe not your way/),
    ).toBeInTheDocument()
  })

  it('has no dismiss button (non-dismissible)', () => {
    render(<ReflectSubViewDisclaimer />)
    expect(screen.queryByRole('button')).toBeNull()
  })

  it('applies the disclaimer container classes', () => {
    const { container } = render(<ReflectSubViewDisclaimer />)
    const wrapper = container.firstElementChild as HTMLElement
    expect(wrapper.className).toContain('border-t')
    expect(wrapper.className).toContain('border-white/[0.08]')
    expect(wrapper.className).toContain('px-4')
    expect(wrapper.className).toContain('py-3')
  })

  it('applies the disclaimer text classes', () => {
    const { container } = render(<ReflectSubViewDisclaimer />)
    const paragraph = container.querySelector('p')
    expect(paragraph?.className).toContain('text-xs')
    expect(paragraph?.className).toContain('leading-relaxed')
    expect(paragraph?.className).toContain('text-white/40')
  })
})
