/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#6D28D9',
        'primary-lt': '#8B5CF6',
        'neutral-bg': '#F5F5F5',
        'text-dark': '#2C3E50',
        'text-light': '#7F8C8D',
        success: '#27AE60',
        warning: '#F39C12',
        danger: '#E74C3C',
        'hero-dark': '#0D0620',
        'hero-mid': '#1E0B3E',
        'hero-deep': '#251248',
        'glow-cyan': '#00D4FF',
        'muted-gray': '#9CA3AF',
        'subtle-gray': '#6B7280',
        'dark-border': '#2a2040',
        'hero-bg': '#08051A',
        'dashboard-dark': '#0f0a1e',
        'dashboard-gradient': '#1a0533',
        'nav-text-dark': '#2B0E4A',
        'nav-hover-light': '#F5F3FF',
        'medal-gold': '#FFD700',
        'medal-silver': '#C0C0C0',
        'medal-bronze': '#CD7F32',
        'spotify-green': '#1DB954',
        'surface-dark': '#1a0f2e',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
        serif: ['Lora', 'ui-serif', 'Georgia'],
        script: ['Caveat', 'cursive'],
      },
      keyframes: {
        'glow-pulse': {
          '0%, 100%': {
            boxShadow:
              '0 0 8px 2px rgba(0, 212, 255, 0.35), 0 0 20px 4px rgba(139, 92, 246, 0.25)',
          },
          '50%': {
            boxShadow:
              '0 0 16px 4px rgba(0, 212, 255, 0.55), 0 0 36px 8px rgba(139, 92, 246, 0.40)',
          },
        },
        'cursor-blink': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        'dropdown-in': {
          '0%': { opacity: '0', transform: 'translateY(-4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-from-right': {
          from: { transform: 'translateX(40px)', opacity: '0' },
          to: { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-from-left': {
          from: { transform: 'translateX(-40px)', opacity: '0' },
          to: { transform: 'translateX(0)', opacity: '1' },
        },
        'golden-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(251, 191, 36, 0.3)' },
          '50%': { boxShadow: '0 0 40px rgba(251, 191, 36, 0.6)' },
        },
        'breathe-expand': {
          '0%': { transform: 'scale(0.6)', opacity: '0.7' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'breathe-contract': {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.6)', opacity: '0.7' },
        },
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'widget-enter': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'waveform-bar-1': {
          '0%, 100%': { height: '4px' },
          '50%': { height: '16px' },
        },
        'waveform-bar-2': {
          '0%, 100%': { height: '8px' },
          '50%': { height: '20px' },
        },
        'waveform-bar-3': {
          '0%, 100%': { height: '6px' },
          '50%': { height: '12px' },
        },
        'artwork-drift': {
          '0%': { backgroundPosition: '50% 50%' },
          '50%': { backgroundPosition: '52% 48%' },
          '100%': { backgroundPosition: '50% 50%' },
        },
        'sound-pulse': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.02)' },
        },
        'scene-pulse': {
          '0%, 100%': { opacity: '0.85' },
          '50%': { opacity: '1' },
        },
        'scene-glow': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.02)' },
        },
        'mood-pulse': {
          '0%, 100%': { opacity: '0.7', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.05)' },
        },
        'slide-from-bottom': {
          from: { transform: 'translateY(40px)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        'celebration-spring': {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '60%': { transform: 'scale(1.1)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'confetti-fall': {
          '0%': { transform: 'translateY(-20px) rotate(0deg)', opacity: '1' },
          '80%': { opacity: '1' },
          '100%': { transform: 'translateY(100vh) rotate(720deg)', opacity: '0' },
        },
        'confetti-burst': {
          '0%': { transform: 'translate(0, 0) scale(1)', opacity: '1' },
          '100%': { transform: 'var(--confetti-end)', opacity: '0' },
        },
        'continue-fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'bell-ring': {
          '0%, 100%': { transform: 'rotate(0)' },
          '25%': { transform: 'rotate(10deg)' },
          '50%': { transform: 'rotate(-10deg)' },
          '75%': { transform: 'rotate(5deg)' },
        },
        'streak-bump': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.1)' },
        },
        'check-fill': {
          '0%': { fillOpacity: '0' },
          '100%': { fillOpacity: '1' },
        },
        'pray-icon-pulse': {
          '0%': { transform: 'scale(1)', filter: 'drop-shadow(0 0 0px rgba(109, 40, 217, 0))' },
          '50%': { transform: 'scale(1.3)', filter: 'drop-shadow(0 0 8px rgba(109, 40, 217, 0.6))' },
          '100%': { transform: 'scale(1)', filter: 'drop-shadow(0 0 0px rgba(109, 40, 217, 0))' },
        },
        'pray-ripple': {
          '0%': { transform: 'scale(1)', opacity: '0.3' },
          '100%': { transform: 'scale(2.5)', opacity: '0' },
        },
        'pray-float-text': {
          '0%': { transform: 'translateY(0)', opacity: '1' },
          '100%': { transform: 'translateY(-20px)', opacity: '0' },
        },
        'mic-pulse': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.1)' },
        },
        'garden-leaf-sway': {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        'garden-butterfly-float': {
          '0%': { transform: 'translate(0, 0)' },
          '25%': { transform: 'translate(8px, -6px)' },
          '50%': { transform: 'translate(16px, 0)' },
          '75%': { transform: 'translate(8px, 6px)' },
          '100%': { transform: 'translate(0, 0)' },
        },
        'garden-water-shimmer': {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        'garden-glow-pulse': {
          '0%, 100%': { opacity: '0.7' },
          '50%': { opacity: '1' },
        },
        'garden-fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'garden-fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'garden-sparkle-rise': {
          '0%': { opacity: '1', transform: 'translateY(0) translateX(0)' },
          '100%': { opacity: '0', transform: 'translateY(-40px) translateX(var(--drift-x, 0px))' },
        },
        'garden-snow-fall': {
          '0%': { transform: 'translateY(-20px) translateX(0)', opacity: '0' },
          '10%': { opacity: '0.8' },
          '100%': { transform: 'translateY(420px) translateX(10px)', opacity: '0' },
        },
        'garden-star-twinkle': {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '0.7' },
        },
        'garden-firefly-glow': {
          '0%, 100%': { opacity: '0.2', transform: 'translate(0, 0)' },
          '25%': { opacity: '0.5', transform: 'translate(3px, -2px)' },
          '50%': { opacity: '0.15', transform: 'translate(-2px, 1px)' },
          '75%': { opacity: '0.45', transform: 'translate(1px, 3px)' },
        },
        'garden-flame-flicker': {
          '0%, 100%': { opacity: '0.8', transform: 'scaleY(1) scaleX(1)' },
          '25%': { opacity: '1', transform: 'scaleY(1.05) scaleX(0.95)' },
          '50%': { opacity: '0.7', transform: 'scaleY(0.95) scaleX(1.05)' },
          '75%': { opacity: '0.9', transform: 'scaleY(1.02) scaleX(0.98)' },
        },
        'garden-seasonal-fade': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'garden-element-fade': {
          '0%': { opacity: '0', transform: 'translateY(5px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'logo-pulse': {
          '0%, 100%': { opacity: '0.2' },
          '50%': { opacity: '0.4' },
        },
        'stagger-enter': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'modal-spring-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'modal-spring-out': {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(0.98)' },
        },
        'toast-spring-in': {
          '0%': { opacity: '0', transform: 'scale(0.8) translateY(8px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        'toast-out': {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(0.95)' },
        },
        'card-pulse': {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.005)' },
          '100%': { transform: 'scale(1)' },
        },
        'content-fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'backdrop-fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'backdrop-fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'drawer-slide-in': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'drawer-slide-out': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'bottom-sheet-slide-in': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'golden-sparkle': {
          '0%': { transform: 'translateY(-10px) scale(0)', opacity: '0' },
          '20%': { opacity: '1', transform: 'translateY(10vh) scale(1)' },
          '80%': { opacity: '0.8' },
          '100%': { transform: 'translateY(100vh) scale(0.5)', opacity: '0' },
        },
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        'glow-float': {
          '0%, 100%': { transform: 'translateY(0) translateX(-50%)' },
          '50%': { transform: 'translateY(-10px) translateX(-50%)' },
        },
      },
      animation: {
        'glow-pulse': 'glow-pulse 2.5s ease-in-out infinite',
        'cursor-blink': 'cursor-blink 1s step-end infinite',
        'dropdown-in': 'dropdown-in 150ms ease-out',
        'slide-from-right': 'slide-from-right 300ms ease-out forwards',
        'slide-from-left': 'slide-from-left 300ms ease-out forwards',
        'golden-glow': 'golden-glow 2s ease-in-out infinite',
        'breathe-expand': 'breathe-expand 4s ease-in-out forwards',
        'breathe-contract': 'breathe-contract 8s ease-in-out forwards',
        'fade-in': 'fade-in 500ms ease-out forwards',
        'waveform-bar-1': 'waveform-bar-1 1.2s ease-in-out infinite',
        'waveform-bar-2': 'waveform-bar-2 1.0s ease-in-out infinite',
        'waveform-bar-3': 'waveform-bar-3 1.4s ease-in-out infinite',
        'artwork-drift': 'artwork-drift 20s ease-in-out infinite',
        'sound-pulse': 'sound-pulse 3s ease-in-out infinite',
        'scene-pulse': 'scene-pulse 4s ease-in-out infinite',
        'scene-glow': 'scene-glow 8s ease-in-out infinite',
        'mood-pulse': 'mood-pulse 3s ease-in-out infinite',
        'slide-from-bottom': 'slide-from-bottom 300ms ease-out forwards',
        'celebration-spring': 'celebration-spring 600ms cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'confetti-fall': 'confetti-fall var(--confetti-duration, 3s) ease-in forwards',
        'confetti-burst': 'confetti-burst 1.5s ease-out forwards',
        'continue-fade-in': 'continue-fade-in 400ms ease-in forwards',
        'bell-ring': 'bell-ring 300ms ease-in-out',
        'streak-bump': 'streak-bump 300ms ease-out',
        'check-fill': 'check-fill 200ms ease-out forwards',
        'pray-icon-pulse': 'pray-icon-pulse 300ms ease-out forwards',
        'pray-ripple': 'pray-ripple 600ms ease-out forwards',
        'pray-float-text': 'pray-float-text 500ms ease-out forwards',
        'mic-pulse': 'mic-pulse 1s ease-in-out infinite',
        'widget-enter': 'widget-enter 400ms ease-out both',
        'garden-leaf-sway': 'garden-leaf-sway 4s ease-in-out infinite alternate',
        'garden-butterfly-float': 'garden-butterfly-float 6s ease-in-out infinite',
        'garden-water-shimmer': 'garden-water-shimmer 3s ease-in-out infinite alternate',
        'garden-glow-pulse': 'garden-glow-pulse 2s ease-in-out infinite alternate',
        'garden-fade-out': 'garden-fade-out 2s ease-in-out forwards',
        'garden-fade-in': 'garden-fade-in 2s ease-in-out forwards',
        'garden-sparkle-rise': 'garden-sparkle-rise 1s ease-out forwards',
        'garden-snow-fall': 'garden-snow-fall 8s linear infinite',
        'garden-star-twinkle': 'garden-star-twinkle 3.5s ease-in-out infinite',
        'garden-firefly-glow': 'garden-firefly-glow 5s ease-in-out infinite',
        'garden-flame-flicker': 'garden-flame-flicker 2s ease-in-out infinite',
        'garden-seasonal-fade': 'garden-seasonal-fade 1s ease-out forwards',
        'garden-element-fade': 'garden-element-fade 500ms ease-out forwards',
        'logo-pulse': 'logo-pulse 2s ease-in-out infinite',
        'stagger-enter': 'stagger-enter 300ms ease-out both',
        'modal-spring-in': 'modal-spring-in 250ms cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'modal-spring-out': 'modal-spring-out 150ms ease-out both',
        'toast-spring-in': 'toast-spring-in 300ms cubic-bezier(0.34, 1.3, 0.64, 1) both',
        'toast-out': 'toast-out 200ms ease-out both',
        'card-pulse': 'card-pulse 300ms ease-in-out',
        'content-fade-in': 'content-fade-in 300ms ease-out both',
        'backdrop-fade-in': 'backdrop-fade-in 200ms ease both',
        'backdrop-fade-out': 'backdrop-fade-out 200ms ease both',
        'drawer-slide-in': 'drawer-slide-in 300ms cubic-bezier(0.34, 1.2, 0.64, 1) both',
        'drawer-slide-out': 'drawer-slide-out 200ms ease-in both',
        'bottom-sheet-slide-in': 'bottom-sheet-slide-in 300ms cubic-bezier(0.34, 1.2, 0.64, 1) both',
        'golden-sparkle': 'golden-sparkle var(--sparkle-duration, 3.5s) ease-in-out forwards',
        'tab-fade-in': 'content-fade-in 200ms ease-out both',
        'slide-from-right-spring': 'slide-from-right 300ms cubic-bezier(0.34, 1.3, 0.64, 1) both',
        'slide-from-bottom-spring': 'slide-from-bottom 300ms cubic-bezier(0.34, 1.3, 0.64, 1) both',
        shimmer: 'shimmer 1.5s ease-in-out infinite',
        'glow-float': 'glow-float 20s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
