/**
 * Non-dismissible AI disclaimer rendered below every successful explanation.
 *
 * The exact text is locked by the spec (BB-30 §"The disclaimer") — do NOT
 * "improve" it. This is the only surface that discloses AI authorship to the
 * user; it must not be hidden behind settings, gated behind tier, or made
 * dismissible.
 */
export function ExplainSubViewDisclaimer() {
  return (
    <div className="border-t border-white/[0.08] px-4 py-3">
      <p className="text-xs leading-relaxed text-white/40">
        This explanation was generated by an AI trained on biblical scholarship.
        It&apos;s one reading of the passage, not the only one. Use it as a
        starting point, not a final answer.
      </p>
    </div>
  )
}
