/**
 * Non-dismissible AI disclaimer rendered below every successful reflection.
 *
 * The exact text is locked by the spec (BB-31 §"The disclaimer") — do NOT
 * "improve" it. The phrase "maybe not your way" is the load-bearing clause
 * that gives the reader permission to disagree with the reflection. It must
 * not be hidden behind settings, gated behind tier, or made dismissible.
 */
export function ReflectSubViewDisclaimer() {
  return (
    <div className="border-t border-white/[0.08] px-4 py-3">
      <p className="text-xs leading-relaxed text-white/40">
        This reflection was generated by an AI. It&apos;s one way this passage
        might land — not the only way, not the best way, and maybe not your way.
      </p>
    </div>
  )
}
