export const AUDIO_CONFIG = {
  MAX_SIMULTANEOUS_SOUNDS: 6,
  DEFAULT_SOUND_VOLUME: 0.6,
  DEFAULT_MASTER_VOLUME: 0.8,
  DEFAULT_FG_BG_BALANCE: 0.5,
  CROSSFADE_DURATION_MS: 1000,
  VOLUME_RAMP_MS: 20,
  SOUND_FADE_IN_MS: 1000,
  SOUND_FADE_OUT_MS: 1000,
  SCENE_CROSSFADE_MS: 3000,
  PILL_FADE_DURATION_MS: 300,
  DRAWER_ANIMATION_MS: 300,
  SLEEP_TIMER_OPTIONS: [15, 30, 45, 60, 90] as const,
  FADE_DURATION_OPTIONS: [5, 10, 15, 30] as const,
} as const

export const AUDIO_BASE_URL = import.meta.env.VITE_AUDIO_BASE_URL ?? '/audio/'
