import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { resolve } from 'path'

// The manifest is now generated by vite-plugin-pwa from the config in vite.config.ts.
// Parse the manifest object from the vite config source to verify its contents.
const configPath = resolve(__dirname, '../../../../vite.config.ts')
const configSource = readFileSync(configPath, 'utf-8')

// Extract the manifest object from the config source via regex
const manifestMatch = configSource.match(/manifest:\s*(\{[\s\S]*?\n\s{6}\}),/m)
if (!manifestMatch) throw new Error('Could not find manifest object in vite.config.ts')

// Convert the TypeScript object literal to JSON-parseable string
const manifestStr = manifestMatch[1]
  .replace(/\/\/.*/g, '') // strip comments
  .replace(/'/g, '"') // single → double quotes
  .replace(/(\w+):/g, '"$1":') // unquoted keys → quoted
  .replace(/"(src|sizes|type|purpose)":/g, '"$1":') // fix icon property keys
  .replace(/,(\s*[}\]])/g, '$1') // strip trailing commas

const manifest = JSON.parse(manifestStr)

describe('PWA manifest (vite.config.ts)', () => {
  it('has all required fields', () => {
    const requiredFields = [
      'name',
      'short_name',
      'description',
      'start_url',
      'display',
      'background_color',
      'theme_color',
      'orientation',
      'categories',
    ]
    for (const field of requiredFields) {
      expect(manifest).toHaveProperty(field)
    }
  })

  it('has correct name and short_name', () => {
    expect(manifest.name).toBe('Worship Room')
    expect(manifest.short_name).toBe('Worship Room')
  })

  it('has correct start_url and display', () => {
    expect(manifest.start_url).toBe('/')
    expect(manifest.display).toBe('standalone')
  })

  it('has correct colors matching BB-39 spec', () => {
    expect(manifest.background_color).toBe('#08051A')
    expect(manifest.theme_color).toBe('#08051A')
  })

  it('has portrait-primary orientation', () => {
    expect(manifest.orientation).toBe('portrait-primary')
  })

  it('has correct categories', () => {
    expect(manifest.categories).toEqual(['books', 'lifestyle', 'education'])
  })

  it('has icons with all required sizes', () => {
    expect(manifest.icons).toBeInstanceOf(Array)
    const sizes = manifest.icons.map((icon: { sizes: string }) => icon.sizes)
    expect(sizes).toContain('192x192')
    expect(sizes).toContain('256x256')
    expect(sizes).toContain('384x384')
    expect(sizes).toContain('512x512')
    expect(sizes).toContain('180x180')
  })

  it('has a maskable icon', () => {
    const maskable = manifest.icons.find(
      (icon: { purpose?: string }) => icon.purpose === 'maskable'
    )
    expect(maskable).toBeDefined()
    expect(maskable.sizes).toBe('512x512')
  })

  it('has icon paths starting with /', () => {
    for (const icon of manifest.icons) {
      expect(icon.src).toMatch(/^\//)
    }
  })

  it('has apple-touch-icon entry', () => {
    const appleIcon = manifest.icons.find(
      (icon: { sizes: string }) => icon.sizes === '180x180'
    )
    expect(appleIcon).toBeDefined()
    expect(appleIcon.src).toBe('/apple-touch-icon.png')
  })
})
