import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, fireEvent } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { ConfirmDialog } from '../ConfirmDialog'

function makeMatchMedia(coarsePointer: boolean) {
  Object.defineProperty(window, 'matchMedia', {
    writable: true,
    configurable: true,
    value: vi.fn().mockImplementation((query: string) => ({
      matches: query === '(pointer: coarse)' ? coarsePointer : false,
      media: query,
      onchange: null,
      addEventListener: vi.fn(),
      removeEventListener: vi.fn(),
      addListener: vi.fn(),
      removeListener: vi.fn(),
      dispatchEvent: vi.fn(),
    })),
  })
}

describe('ConfirmDialog', () => {
  const defaults = {
    isOpen: true,
    title: 'Are you sure?',
    body: 'This action will do something.',
    confirmLabel: 'Confirm',
    onConfirm: vi.fn(),
    onCancel: vi.fn(),
  }

  beforeEach(() => {
    vi.clearAllMocks()
    makeMatchMedia(false)
  })

  it('renders nothing when isOpen=false', () => {
    render(<ConfirmDialog {...defaults} isOpen={false} />)
    expect(screen.queryByText('Are you sure?')).not.toBeInTheDocument()
  })

  it('renders title and body when isOpen=true', () => {
    render(<ConfirmDialog {...defaults} />)
    expect(screen.getByText('Are you sure?')).toBeInTheDocument()
    expect(screen.getByText('This action will do something.')).toBeInTheDocument()
  })

  it('confirm button click fires onConfirm', async () => {
    const onConfirm = vi.fn()
    const onCancel = vi.fn()
    render(<ConfirmDialog {...defaults} onConfirm={onConfirm} onCancel={onCancel} />)
    await userEvent.click(screen.getByRole('button', { name: 'Confirm' }))
    expect(onConfirm).toHaveBeenCalledTimes(1)
    expect(onCancel).not.toHaveBeenCalled()
  })

  it('cancel button click fires onCancel', async () => {
    const onCancel = vi.fn()
    render(<ConfirmDialog {...defaults} onCancel={onCancel} />)
    await userEvent.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(onCancel).toHaveBeenCalledTimes(1)
  })

  it('Escape key fires onCancel via focus trap', async () => {
    const onCancel = vi.fn()
    render(<ConfirmDialog {...defaults} onCancel={onCancel} />)
    await userEvent.keyboard('{Escape}')
    expect(onCancel).toHaveBeenCalled()
  })

  it('destructive variant applies red button class', () => {
    render(<ConfirmDialog {...defaults} variant="destructive" />)
    const button = screen.getByRole('button', { name: 'Confirm' })
    expect(button.className).toContain('bg-red-500')
  })

  it('default variant applies canonical frosted subtle treatment (not deprecated bg-primary)', () => {
    render(<ConfirmDialog {...defaults} variant="default" />)
    const button = screen.getByRole('button', { name: 'Confirm' })
    expect(button.className).toContain('bg-white/[0.12]')
    expect(button.className).toContain('border-white/[0.20]')
    expect(button.className).not.toContain('bg-primary')
  })

  it('role="alertdialog" wires aria-labelledby and aria-describedby to the title and body elements', () => {
    render(<ConfirmDialog {...defaults} />)
    const dialog = screen.getByRole('alertdialog')
    expect(dialog).toHaveAttribute('aria-modal', 'true')

    // The IDs themselves are generated by React.useId() and intentionally not
    // hardcoded — assert on the wiring (the referenced elements contain the
    // expected text), not the specific ID strings.
    const labelledBy = dialog.getAttribute('aria-labelledby')
    const describedBy = dialog.getAttribute('aria-describedby')
    expect(labelledBy).toBeTruthy()
    expect(describedBy).toBeTruthy()
    expect(document.getElementById(labelledBy!)).toHaveTextContent('Are you sure?')
    expect(document.getElementById(describedBy!)).toHaveTextContent('This action will do something.')
  })

  it('two simultaneously-mounted dialogs generate distinct aria IDs (no collision)', () => {
    // Regression guard: pre-fix the component used static IDs ("confirm-dialog-title",
    // "confirm-dialog-body"). Two open dialogs would collide and break aria-labelledby
    // resolution for screen readers. useId() must keep them unique.
    render(
      <>
        <ConfirmDialog {...defaults} title="Dialog one" body="Body one" />
        <ConfirmDialog {...defaults} title="Dialog two" body="Body two" />
      </>,
    )
    const dialogs = screen.getAllByRole('alertdialog')
    expect(dialogs).toHaveLength(2)

    const labels = dialogs.map((d) => d.getAttribute('aria-labelledby'))
    const descs = dialogs.map((d) => d.getAttribute('aria-describedby'))

    expect(labels[0]).toBeTruthy()
    expect(labels[1]).toBeTruthy()
    expect(labels[0]).not.toBe(labels[1])

    expect(descs[0]).toBeTruthy()
    expect(descs[1]).toBeTruthy()
    expect(descs[0]).not.toBe(descs[1])

    // And the IDs must each resolve to the correct element (not just be unique strings)
    expect(document.getElementById(labels[0]!)).toHaveTextContent('Dialog one')
    expect(document.getElementById(labels[1]!)).toHaveTextContent('Dialog two')
  })

  it('backdrop-click on desktop pointer fires onCancel', () => {
    makeMatchMedia(false)
    const onCancel = vi.fn()
    const { container } = render(<ConfirmDialog {...defaults} onCancel={onCancel} />)
    const backdrop = container.querySelector('[aria-hidden="true"]')!
    fireEvent.click(backdrop)
    expect(onCancel).toHaveBeenCalledTimes(1)
  })

  it('backdrop-click on coarse pointer (mobile) does NOT fire onCancel', () => {
    makeMatchMedia(true)
    const onCancel = vi.fn()
    const { container } = render(<ConfirmDialog {...defaults} onCancel={onCancel} />)
    const backdrop = container.querySelector('[aria-hidden="true"]')!
    fireEvent.click(backdrop)
    expect(onCancel).not.toHaveBeenCalled()
  })
})
